apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: zerotrust
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: root
  MONGODB_URI: mongodb://root:root@mongodb:27017/zerotrust_database?authSource=admin