apiVersion: v1
kind: ServiceAccount      # ServiceAccount: Pod 내에서 프로세스 인증, 권한
metadata:
  name: mongodb-sa
  namespace: zerotrust
automountServiceAccountToken: false
# Pod 안에서 K8s API Server와 통신 마운트를 false 비활성화