apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: zerotrust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: a67422830/user-service:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              value: mongodb://mongodb:27017/zerotrust_database