apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
  namespace: zerotrust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
    
      serviceAccountName: event-service-sa
      automountServiceAccountToken: false

      containers:
        - name: event-service
          image: a67422830/event-service:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGODB_URI