apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-test-client-to-event-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.eventService.name }}
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - "cluster.local/ns/{{ .Release.Namespace }}/sa/{{ .Values.testClient.serviceAccountName }}"