apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.mongodb.auth.username | quote }}
  password: {{ .Values.mongodb.auth.password | quote }}