apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-helm
spec:
  capacity:
    storage: {{ .Values.mongodb.storage.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.mongodb.storage.storageClassName }}
  hostPath:
    path: {{ .Values.mongodb.storage.hostPath }}