apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-userservice-to-mongodb
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.mongodb.name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.userService.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.mongodb.service.port }}