apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-testclient-egress-to-userservice
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.testClient.name }}
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.userService.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.userService.service.port }}