apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-client-read-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.testClient.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test-client-read-role